# Generated by Django 3.1.1 on 2020-09-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='useInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('phone', models.CharField(max_length=16, verbose_name='电话')),
                ('sex', models.CharField(max_length=16, verbose_name='性别')),
                ('email', models.EmailField(max_length=64, verbose_name='邮箱地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户信息表',
            },
        ),
    ]
